server:
  error:
    include-message: always
    include-stacktrace: never
    include-binding-errors: always

spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/rainparksolutions
    username: techprodb_user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
